// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/hermes.proto

package hermespb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecutionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full path to the command to execute inside the container
	// Example: "/opt/NONMEM/nm76/run/nmfe76"
	Command string `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	// Arguments to pass to the command
	// Example: ["model.mod", "model.lst"]
	Args []string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	// Working directory inside the container (where files are written)
	// Example: "/workspace"
	WorkingDir string `protobuf:"bytes,3,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	// Files to inject into the container
	// Key: relative path from working_dir
	// Value: file content as bytes
	// Example: {"model.mod": <bytes>, "data.csv": <bytes>, "license.lic": <bytes>}
	Files map[string][]byte `protobuf:"bytes,4,rep,name=files,proto3" json:"files,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// File patterns to retain after execution (glob patterns)
	// These files are collected and returned in the response stream
	// Example: ["*.lst", "*.ext", "*.cov", "FDATA", "output/*.xml"]
	Retain []string `protobuf:"bytes,5,rep,name=retain,proto3" json:"retain,omitempty"`
	// Docker image to use for execution
	// Example: "pharmalytica/nonmem:nm76"
	ContainerImage string `protobuf:"bytes,6,opt,name=container_image,json=containerImage,proto3" json:"container_image,omitempty"`
	// Environment variables to set in the container
	// Example: {"OMP_NUM_THREADS": "4", "NONMEM_LICENSE_FILE": "/workspace/license.lic"}
	Environment map[string]string `protobuf:"bytes,7,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Resource limits (optional)
	Limits *ResourceLimits `protobuf:"bytes,8,opt,name=limits,proto3" json:"limits,omitempty"`
	// Execution ID for tracking and cancellation (optional)
	// If provided, used for audit trail correlation and workspace isolation
	// If empty, server generates a UUID
	// Client should provide this to align with audit log entries
	// Example: "audit-entry-12345" or "janus-job-abc-def"
	ExecutionId   string `protobuf:"bytes,9,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionRequest) Reset() {
	*x = ExecutionRequest{}
	mi := &file_proto_hermes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionRequest) ProtoMessage() {}

func (x *ExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hermes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionRequest.ProtoReflect.Descriptor instead.
func (*ExecutionRequest) Descriptor() ([]byte, []int) {
	return file_proto_hermes_proto_rawDescGZIP(), []int{0}
}

func (x *ExecutionRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecutionRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ExecutionRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *ExecutionRequest) GetFiles() map[string][]byte {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ExecutionRequest) GetRetain() []string {
	if x != nil {
		return x.Retain
	}
	return nil
}

func (x *ExecutionRequest) GetContainerImage() string {
	if x != nil {
		return x.ContainerImage
	}
	return ""
}

func (x *ExecutionRequest) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *ExecutionRequest) GetLimits() *ResourceLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *ExecutionRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type ResourceLimits struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CPU limit (e.g., "4" for 4 cores, "2.5" for 2.5 cores)
	// Used for request validation and per-execution CPU shares
	CpuLimit string `protobuf:"bytes,1,opt,name=cpu_limit,json=cpuLimit,proto3" json:"cpu_limit,omitempty"`
	// Memory limit (e.g., "8G" for 8 gigabytes, "512M" for 512 megabytes)
	// Used for request validation and per-execution memory limits
	MemoryLimit string `protobuf:"bytes,2,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"`
	// Execution timeout (seconds)
	// Per-execution timeout (not container-level)
	TimeoutSeconds int64 `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResourceLimits) Reset() {
	*x = ResourceLimits{}
	mi := &file_proto_hermes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceLimits) ProtoMessage() {}

func (x *ResourceLimits) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hermes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceLimits.ProtoReflect.Descriptor instead.
func (*ResourceLimits) Descriptor() ([]byte, []int) {
	return file_proto_hermes_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceLimits) GetCpuLimit() string {
	if x != nil {
		return x.CpuLimit
	}
	return ""
}

func (x *ResourceLimits) GetMemoryLimit() string {
	if x != nil {
		return x.MemoryLimit
	}
	return ""
}

func (x *ResourceLimits) GetTimeoutSeconds() int64 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type ExecutionEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Execution ID for tracking
	ExecutionId string `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	// Event timestamp (Unix epoch)
	Timestamp int64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*ExecutionEvent_Started
	//	*ExecutionEvent_Stdout
	//	*ExecutionEvent_Stderr
	//	*ExecutionEvent_FileChunk
	//	*ExecutionEvent_Complete
	//	*ExecutionEvent_Error
	//	*ExecutionEvent_AuditLog
	Event         isExecutionEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionEvent) Reset() {
	*x = ExecutionEvent{}
	mi := &file_proto_hermes_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionEvent) ProtoMessage() {}

func (x *ExecutionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hermes_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionEvent.ProtoReflect.Descriptor instead.
func (*ExecutionEvent) Descriptor() ([]byte, []int) {
	return file_proto_hermes_proto_rawDescGZIP(), []int{2}
}

func (x *ExecutionEvent) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ExecutionEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ExecutionEvent) GetEvent() isExecutionEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ExecutionEvent) GetStarted() *ContainerStarted {
	if x != nil {
		if x, ok := x.Event.(*ExecutionEvent_Started); ok {
			return x.Started
		}
	}
	return nil
}

func (x *ExecutionEvent) GetStdout() *LogLine {
	if x != nil {
		if x, ok := x.Event.(*ExecutionEvent_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *ExecutionEvent) GetStderr() *LogLine {
	if x != nil {
		if x, ok := x.Event.(*ExecutionEvent_Stderr); ok {
			return x.Stderr
		}
	}
	return nil
}

func (x *ExecutionEvent) GetFileChunk() *FileChunk {
	if x != nil {
		if x, ok := x.Event.(*ExecutionEvent_FileChunk); ok {
			return x.FileChunk
		}
	}
	return nil
}

func (x *ExecutionEvent) GetComplete() *ExecutionComplete {
	if x != nil {
		if x, ok := x.Event.(*ExecutionEvent_Complete); ok {
			return x.Complete
		}
	}
	return nil
}

func (x *ExecutionEvent) GetError() *ExecutionError {
	if x != nil {
		if x, ok := x.Event.(*ExecutionEvent_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ExecutionEvent) GetAuditLog() *AuditLogEntry {
	if x != nil {
		if x, ok := x.Event.(*ExecutionEvent_AuditLog); ok {
			return x.AuditLog
		}
	}
	return nil
}

type isExecutionEvent_Event interface {
	isExecutionEvent_Event()
}

type ExecutionEvent_Started struct {
	// Container started
	Started *ContainerStarted `protobuf:"bytes,10,opt,name=started,proto3,oneof"`
}

type ExecutionEvent_Stdout struct {
	// Standard output line
	Stdout *LogLine `protobuf:"bytes,11,opt,name=stdout,proto3,oneof"`
}

type ExecutionEvent_Stderr struct {
	// Standard error line
	Stderr *LogLine `protobuf:"bytes,12,opt,name=stderr,proto3,oneof"`
}

type ExecutionEvent_FileChunk struct {
	// Result file being streamed
	FileChunk *FileChunk `protobuf:"bytes,13,opt,name=file_chunk,json=fileChunk,proto3,oneof"`
}

type ExecutionEvent_Complete struct {
	// Execution completed
	Complete *ExecutionComplete `protobuf:"bytes,14,opt,name=complete,proto3,oneof"`
}

type ExecutionEvent_Error struct {
	// Execution failed
	Error *ExecutionError `protobuf:"bytes,15,opt,name=error,proto3,oneof"`
}

type ExecutionEvent_AuditLog struct {
	// Audit log entry (GxP compliance)
	AuditLog *AuditLogEntry `protobuf:"bytes,16,opt,name=audit_log,json=auditLog,proto3,oneof"`
}

func (*ExecutionEvent_Started) isExecutionEvent_Event() {}

func (*ExecutionEvent_Stdout) isExecutionEvent_Event() {}

func (*ExecutionEvent_Stderr) isExecutionEvent_Event() {}

func (*ExecutionEvent_FileChunk) isExecutionEvent_Event() {}

func (*ExecutionEvent_Complete) isExecutionEvent_Event() {}

func (*ExecutionEvent_Error) isExecutionEvent_Event() {}

func (*ExecutionEvent_AuditLog) isExecutionEvent_Event() {}

type ContainerStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerStarted) Reset() {
	*x = ContainerStarted{}
	mi := &file_proto_hermes_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerStarted) ProtoMessage() {}

func (x *ContainerStarted) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hermes_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerStarted.ProtoReflect.Descriptor instead.
func (*ContainerStarted) Descriptor() ([]byte, []int) {
	return file_proto_hermes_proto_rawDescGZIP(), []int{3}
}

func (x *ContainerStarted) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ContainerStarted) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type LogLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line          string                 `protobuf:"bytes,1,opt,name=line,proto3" json:"line,omitempty"`
	LineNumber    int32                  `protobuf:"varint,2,opt,name=line_number,json=lineNumber,proto3" json:"line_number,omitempty"` // Sequential line number
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLine) Reset() {
	*x = LogLine{}
	mi := &file_proto_hermes_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLine) ProtoMessage() {}

func (x *LogLine) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hermes_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLine.ProtoReflect.Descriptor instead.
func (*LogLine) Descriptor() ([]byte, []int) {
	return file_proto_hermes_proto_rawDescGZIP(), []int{4}
}

func (x *LogLine) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

func (x *LogLine) GetLineNumber() int32 {
	if x != nil {
		return x.LineNumber
	}
	return 0
}

type FileChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Relative path from working_dir
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Chunk of file content
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3" json:"chunk,omitempty"`
	// Is this the final chunk for this file?
	IsFinal bool `protobuf:"varint,3,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	// Total file size (if known)
	TotalSize     int64 `protobuf:"varint,4,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_proto_hermes_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hermes_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_proto_hermes_proto_rawDescGZIP(), []int{5}
}

func (x *FileChunk) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileChunk) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *FileChunk) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *FileChunk) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

type ExecutionComplete struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExitCode       int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	RuntimeSeconds int64                  `protobuf:"varint,2,opt,name=runtime_seconds,json=runtimeSeconds,proto3" json:"runtime_seconds,omitempty"`
	FilesCollected int32                  `protobuf:"varint,3,opt,name=files_collected,json=filesCollected,proto3" json:"files_collected,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecutionComplete) Reset() {
	*x = ExecutionComplete{}
	mi := &file_proto_hermes_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionComplete) ProtoMessage() {}

func (x *ExecutionComplete) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hermes_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionComplete.ProtoReflect.Descriptor instead.
func (*ExecutionComplete) Descriptor() ([]byte, []int) {
	return file_proto_hermes_proto_rawDescGZIP(), []int{6}
}

func (x *ExecutionComplete) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecutionComplete) GetRuntimeSeconds() int64 {
	if x != nil {
		return x.RuntimeSeconds
	}
	return 0
}

func (x *ExecutionComplete) GetFilesCollected() int32 {
	if x != nil {
		return x.FilesCollected
	}
	return 0
}

type ExecutionError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionError) Reset() {
	*x = ExecutionError{}
	mi := &file_proto_hermes_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionError) ProtoMessage() {}

func (x *ExecutionError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hermes_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionError.ProtoReflect.Descriptor instead.
func (*ExecutionError) Descriptor() ([]byte, []int) {
	return file_proto_hermes_proto_rawDescGZIP(), []int{7}
}

func (x *ExecutionError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExecutionError) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

type AuditLogEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timestamp in RFC3339Nano format
	Timestamp string `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Log level (INFO, WARNING, ERROR, AUDIT)
	Level string `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	// Execution ID (correlation)
	ExecutionId string `protobuf:"bytes,3,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	// Log message
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// Structured data as JSON string
	// Contains additional context like command, args, exit_code, etc.
	DataJson      string `protobuf:"bytes,5,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditLogEntry) Reset() {
	*x = AuditLogEntry{}
	mi := &file_proto_hermes_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLogEntry) ProtoMessage() {}

func (x *AuditLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hermes_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLogEntry.ProtoReflect.Descriptor instead.
func (*AuditLogEntry) Descriptor() ([]byte, []int) {
	return file_proto_hermes_proto_rawDescGZIP(), []int{8}
}

func (x *AuditLogEntry) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *AuditLogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *AuditLogEntry) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *AuditLogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AuditLogEntry) GetDataJson() string {
	if x != nil {
		return x.DataJson
	}
	return ""
}

type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_proto_hermes_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hermes_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_proto_hermes_proto_rawDescGZIP(), []int{9}
}

func (x *CancelRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type CancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cancelled     bool                   `protobuf:"varint,1,opt,name=cancelled,proto3" json:"cancelled,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_proto_hermes_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hermes_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_proto_hermes_proto_rawDescGZIP(), []int{10}
}

func (x *CancelResponse) GetCancelled() bool {
	if x != nil {
		return x.Cancelled
	}
	return false
}

func (x *CancelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_hermes_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hermes_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_hermes_proto_rawDescGZIP(), []int{11}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Docker        *DockerStatus          `protobuf:"bytes,3,opt,name=docker,proto3" json:"docker,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_hermes_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hermes_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_hermes_proto_rawDescGZIP(), []int{12}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetDocker() *DockerStatus {
	if x != nil {
		return x.Docker
	}
	return nil
}

type DockerStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Available     bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DockerStatus) Reset() {
	*x = DockerStatus{}
	mi := &file_proto_hermes_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DockerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerStatus) ProtoMessage() {}

func (x *DockerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hermes_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockerStatus.ProtoReflect.Descriptor instead.
func (*DockerStatus) Descriptor() ([]byte, []int) {
	return file_proto_hermes_proto_rawDescGZIP(), []int{13}
}

func (x *DockerStatus) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *DockerStatus) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type VersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionRequest) Reset() {
	*x = VersionRequest{}
	mi := &file_proto_hermes_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionRequest) ProtoMessage() {}

func (x *VersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hermes_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionRequest.ProtoReflect.Descriptor instead.
func (*VersionRequest) Descriptor() ([]byte, []int) {
	return file_proto_hermes_proto_rawDescGZIP(), []int{14}
}

type VersionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Semantic version (e.g., "1.0.0", "dev")
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// Git commit hash
	GitCommit string `protobuf:"bytes,2,opt,name=git_commit,json=gitCommit,proto3" json:"git_commit,omitempty"`
	// Build date in RFC3339 format
	BuildDate string `protobuf:"bytes,3,opt,name=build_date,json=buildDate,proto3" json:"build_date,omitempty"`
	// Go version used to build
	GoVersion string `protobuf:"bytes,4,opt,name=go_version,json=goVersion,proto3" json:"go_version,omitempty"`
	// Platform (e.g., "linux/amd64", "windows/amd64")
	Platform      string `protobuf:"bytes,5,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionResponse) Reset() {
	*x = VersionResponse{}
	mi := &file_proto_hermes_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionResponse) ProtoMessage() {}

func (x *VersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hermes_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionResponse.ProtoReflect.Descriptor instead.
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return file_proto_hermes_proto_rawDescGZIP(), []int{15}
}

func (x *VersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *VersionResponse) GetGitCommit() string {
	if x != nil {
		return x.GitCommit
	}
	return ""
}

func (x *VersionResponse) GetBuildDate() string {
	if x != nil {
		return x.BuildDate
	}
	return ""
}

func (x *VersionResponse) GetGoVersion() string {
	if x != nil {
		return x.GoVersion
	}
	return ""
}

func (x *VersionResponse) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

var File_proto_hermes_proto protoreflect.FileDescriptor

const file_proto_hermes_proto_rawDesc = "" +
	"\n" +
	"\x12proto/hermes.proto\x12\x06hermes\"\xf7\x03\n" +
	"\x10ExecutionRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12\x1f\n" +
	"\vworking_dir\x18\x03 \x01(\tR\n" +
	"workingDir\x129\n" +
	"\x05files\x18\x04 \x03(\v2#.hermes.ExecutionRequest.FilesEntryR\x05files\x12\x16\n" +
	"\x06retain\x18\x05 \x03(\tR\x06retain\x12'\n" +
	"\x0fcontainer_image\x18\x06 \x01(\tR\x0econtainerImage\x12K\n" +
	"\venvironment\x18\a \x03(\v2).hermes.ExecutionRequest.EnvironmentEntryR\venvironment\x12.\n" +
	"\x06limits\x18\b \x01(\v2\x16.hermes.ResourceLimitsR\x06limits\x12!\n" +
	"\fexecution_id\x18\t \x01(\tR\vexecutionId\x1a8\n" +
	"\n" +
	"FilesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1a>\n" +
	"\x10EnvironmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"y\n" +
	"\x0eResourceLimits\x12\x1b\n" +
	"\tcpu_limit\x18\x01 \x01(\tR\bcpuLimit\x12!\n" +
	"\fmemory_limit\x18\x02 \x01(\tR\vmemoryLimit\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x03R\x0etimeoutSeconds\"\xb9\x03\n" +
	"\x0eExecutionEvent\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x124\n" +
	"\astarted\x18\n" +
	" \x01(\v2\x18.hermes.ContainerStartedH\x00R\astarted\x12)\n" +
	"\x06stdout\x18\v \x01(\v2\x0f.hermes.LogLineH\x00R\x06stdout\x12)\n" +
	"\x06stderr\x18\f \x01(\v2\x0f.hermes.LogLineH\x00R\x06stderr\x122\n" +
	"\n" +
	"file_chunk\x18\r \x01(\v2\x11.hermes.FileChunkH\x00R\tfileChunk\x127\n" +
	"\bcomplete\x18\x0e \x01(\v2\x19.hermes.ExecutionCompleteH\x00R\bcomplete\x12.\n" +
	"\x05error\x18\x0f \x01(\v2\x16.hermes.ExecutionErrorH\x00R\x05error\x124\n" +
	"\taudit_log\x18\x10 \x01(\v2\x15.hermes.AuditLogEntryH\x00R\bauditLogB\a\n" +
	"\x05event\"K\n" +
	"\x10ContainerStarted\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\">\n" +
	"\aLogLine\x12\x12\n" +
	"\x04line\x18\x01 \x01(\tR\x04line\x12\x1f\n" +
	"\vline_number\x18\x02 \x01(\x05R\n" +
	"lineNumber\"o\n" +
	"\tFileChunk\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x14\n" +
	"\x05chunk\x18\x02 \x01(\fR\x05chunk\x12\x19\n" +
	"\bis_final\x18\x03 \x01(\bR\aisFinal\x12\x1d\n" +
	"\n" +
	"total_size\x18\x04 \x01(\x03R\ttotalSize\"\x82\x01\n" +
	"\x11ExecutionComplete\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12'\n" +
	"\x0fruntime_seconds\x18\x02 \x01(\x03R\x0eruntimeSeconds\x12'\n" +
	"\x0ffiles_collected\x18\x03 \x01(\x05R\x0efilesCollected\"I\n" +
	"\x0eExecutionError\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\"\x9d\x01\n" +
	"\rAuditLogEntry\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12!\n" +
	"\fexecution_id\x18\x03 \x01(\tR\vexecutionId\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1b\n" +
	"\tdata_json\x18\x05 \x01(\tR\bdataJson\"2\n" +
	"\rCancelRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\"H\n" +
	"\x0eCancelResponse\x12\x1c\n" +
	"\tcancelled\x18\x01 \x01(\bR\tcancelled\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x0f\n" +
	"\rHealthRequest\"r\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12,\n" +
	"\x06docker\x18\x03 \x01(\v2\x14.hermes.DockerStatusR\x06docker\"F\n" +
	"\fDockerStatus\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\x10\n" +
	"\x0eVersionRequest\"\xa4\x01\n" +
	"\x0fVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"git_commit\x18\x02 \x01(\tR\tgitCommit\x12\x1d\n" +
	"\n" +
	"build_date\x18\x03 \x01(\tR\tbuildDate\x12\x1d\n" +
	"\n" +
	"go_version\x18\x04 \x01(\tR\tgoVersion\x12\x1a\n" +
	"\bplatform\x18\x05 \x01(\tR\bplatform2\xf8\x01\n" +
	"\x06Hermes\x12=\n" +
	"\aExecute\x12\x18.hermes.ExecutionRequest\x1a\x16.hermes.ExecutionEvent0\x01\x127\n" +
	"\x06Cancel\x12\x15.hermes.CancelRequest\x1a\x16.hermes.CancelResponse\x127\n" +
	"\x06Health\x12\x15.hermes.HealthRequest\x1a\x16.hermes.HealthResponse\x12=\n" +
	"\n" +
	"GetVersion\x12\x16.hermes.VersionRequest\x1a\x17.hermes.VersionResponseB/Z-github.com/pharmalytica/hermes/proto;hermespbb\x06proto3"

var (
	file_proto_hermes_proto_rawDescOnce sync.Once
	file_proto_hermes_proto_rawDescData []byte
)

func file_proto_hermes_proto_rawDescGZIP() []byte {
	file_proto_hermes_proto_rawDescOnce.Do(func() {
		file_proto_hermes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_hermes_proto_rawDesc), len(file_proto_hermes_proto_rawDesc)))
	})
	return file_proto_hermes_proto_rawDescData
}

var file_proto_hermes_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_hermes_proto_goTypes = []any{
	(*ExecutionRequest)(nil),  // 0: hermes.ExecutionRequest
	(*ResourceLimits)(nil),    // 1: hermes.ResourceLimits
	(*ExecutionEvent)(nil),    // 2: hermes.ExecutionEvent
	(*ContainerStarted)(nil),  // 3: hermes.ContainerStarted
	(*LogLine)(nil),           // 4: hermes.LogLine
	(*FileChunk)(nil),         // 5: hermes.FileChunk
	(*ExecutionComplete)(nil), // 6: hermes.ExecutionComplete
	(*ExecutionError)(nil),    // 7: hermes.ExecutionError
	(*AuditLogEntry)(nil),     // 8: hermes.AuditLogEntry
	(*CancelRequest)(nil),     // 9: hermes.CancelRequest
	(*CancelResponse)(nil),    // 10: hermes.CancelResponse
	(*HealthRequest)(nil),     // 11: hermes.HealthRequest
	(*HealthResponse)(nil),    // 12: hermes.HealthResponse
	(*DockerStatus)(nil),      // 13: hermes.DockerStatus
	(*VersionRequest)(nil),    // 14: hermes.VersionRequest
	(*VersionResponse)(nil),   // 15: hermes.VersionResponse
	nil,                       // 16: hermes.ExecutionRequest.FilesEntry
	nil,                       // 17: hermes.ExecutionRequest.EnvironmentEntry
}
var file_proto_hermes_proto_depIdxs = []int32{
	16, // 0: hermes.ExecutionRequest.files:type_name -> hermes.ExecutionRequest.FilesEntry
	17, // 1: hermes.ExecutionRequest.environment:type_name -> hermes.ExecutionRequest.EnvironmentEntry
	1,  // 2: hermes.ExecutionRequest.limits:type_name -> hermes.ResourceLimits
	3,  // 3: hermes.ExecutionEvent.started:type_name -> hermes.ContainerStarted
	4,  // 4: hermes.ExecutionEvent.stdout:type_name -> hermes.LogLine
	4,  // 5: hermes.ExecutionEvent.stderr:type_name -> hermes.LogLine
	5,  // 6: hermes.ExecutionEvent.file_chunk:type_name -> hermes.FileChunk
	6,  // 7: hermes.ExecutionEvent.complete:type_name -> hermes.ExecutionComplete
	7,  // 8: hermes.ExecutionEvent.error:type_name -> hermes.ExecutionError
	8,  // 9: hermes.ExecutionEvent.audit_log:type_name -> hermes.AuditLogEntry
	13, // 10: hermes.HealthResponse.docker:type_name -> hermes.DockerStatus
	0,  // 11: hermes.Hermes.Execute:input_type -> hermes.ExecutionRequest
	9,  // 12: hermes.Hermes.Cancel:input_type -> hermes.CancelRequest
	11, // 13: hermes.Hermes.Health:input_type -> hermes.HealthRequest
	14, // 14: hermes.Hermes.GetVersion:input_type -> hermes.VersionRequest
	2,  // 15: hermes.Hermes.Execute:output_type -> hermes.ExecutionEvent
	10, // 16: hermes.Hermes.Cancel:output_type -> hermes.CancelResponse
	12, // 17: hermes.Hermes.Health:output_type -> hermes.HealthResponse
	15, // 18: hermes.Hermes.GetVersion:output_type -> hermes.VersionResponse
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_hermes_proto_init() }
func file_proto_hermes_proto_init() {
	if File_proto_hermes_proto != nil {
		return
	}
	file_proto_hermes_proto_msgTypes[2].OneofWrappers = []any{
		(*ExecutionEvent_Started)(nil),
		(*ExecutionEvent_Stdout)(nil),
		(*ExecutionEvent_Stderr)(nil),
		(*ExecutionEvent_FileChunk)(nil),
		(*ExecutionEvent_Complete)(nil),
		(*ExecutionEvent_Error)(nil),
		(*ExecutionEvent_AuditLog)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_hermes_proto_rawDesc), len(file_proto_hermes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_hermes_proto_goTypes,
		DependencyIndexes: file_proto_hermes_proto_depIdxs,
		MessageInfos:      file_proto_hermes_proto_msgTypes,
	}.Build()
	File_proto_hermes_proto = out.File
	file_proto_hermes_proto_goTypes = nil
	file_proto_hermes_proto_depIdxs = nil
}
